// import { Inter } from "next/font/google";
// import "./globals.scss";
// import "./index.css";
// import { Toaster } from "react-hot-toast";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html className="html" lang="fa">
//       <body className={inter.className}>
//         <Toaster position="top-center" />
//         {children}
//       </body>
//     </html>
//   );
// }
